AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  spamdetectorLF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: >-
        arn:aws:iam::452853680688:role/service-role/spam-detector-LF1-role-gqy0sjww
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
      Environment:
        Variables:
          ENDPOINT_NAME: sms-spam-classifier-mxnet-2021-04-06-03-17-06-255
      Layers:
        - >-
          arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python38-SciPy1x:29
  Bucket1:
    Type: 'AWS::S3::Bucket'

